### ISSUE TITLE
卡在了第一步拼命加载中请问是怎么回事？

### ISSUE THREAD

**Issue by adonis-wyc** [mikehumix/autoplay#2]
![image](https://user-images.githubusercontent.com/41361698/148881773-43ead4a0-0787-401a-87ba-eaf060011ed3.png)

**Comment by adonis-wyc** [comment]
而且第一步页面缺少了设置按钮
![image](https://user-images.githubusercontent.com/41361698/148882152-9cbf14bb-0860-47c8-be6c-f479f7ea412b.png)

**Comment by mikehumix** [comment]
感谢使用，那是因为引用的网易云api失效导致的，建议更换有效的网易云api或者自行搭建！
推荐：https://github.com/Binaryify/NeteaseCloudMusicApi
